site_name: MaterialValues
pages:
- Presentation: index.md
- Style:
    - Colors: style/colors.md
    - Icons: style/icons.md
    - Typography: style/typography.md
- Layout:
    - Metrics & keylines: layout/keylines.md
theme: flatly
